### ISSUE TITLE
Timed recurring jobs

### ISSUE THREAD

**Issue by cirode** [buildkite/feedback#61] opened 2014-10-09 01:18 UTC
We have the need to run recurring jobs using our CI agents in order to do certain tasks

I would love to be able to configure a pipeline to be able to be triggered not by a code push, but by a crontab style setup

We have a workaround for this with managed crontabs and api calls.. however having it built into the interface would be much better

**Comment by timmipetit** [comment] 2015-06-02 14:48
:+1:

**Comment by colinbankier** [comment] 2015-07-14 01:08
:+1:

**Comment by tspecht** [comment] 2015-11-10 13:46
I'm assuming this one is not live yet? Any ETA?

**Comment by keithpitt** [comment] 2015-11-11 06:27
Hey @tspecht - not yet :( But we're working on it. In the mean time, `cron` and the "Create a build" API works pretty well: https://buildkite.com/docs/api/builds#create-a-build

**Comment by vaughandroid** [comment] 2016-03-17 10:21
Would love to see this too. :+1:

**Comment by joho** [comment] 2016-04-20 04:14
I've got two specific use cases at work that could benefit greatly from this addition /cc @mtibben @lwc

**Comment by mdub** [comment] 2016-05-10 22:54
+1

**Comment by keithpitt** [comment] 2016-05-10 23:26
🔜

Here's a question for those that have replied to this. I've been thinking about how to implement recurring jobs, and one thing I'm not entirely sure how to handle is "who" triggers the build. Ideally every build is linked to a user in Buildkite, would it be fair to select a user from to trigger the build as? Or should it use the user from the commit? (of it it's HEAD, the user of the latest commit)

**Comment by mtibben** [comment] 2016-05-10 23:40
For the use-cases I'm thinking of, it would make sense to link it to the user who created the recurring job

**Comment by vaughandroid** [comment] 2016-05-11 07:16
@keithpitt Assuming it will say "Triggered via timed job" or similar then I think it's fine to link it to the user who created the recurring job.

**Comment by op-and** [comment] 2016-07-01 15:47
@keithpitt Wondering if there was an update on the issue? We are using buildlkite and would like to be able to kick-off nightly builds.

**Comment by keithpitt** [comment] 2016-07-01 22:14
@op-and hey! So we've made some massive moves on this. We've rolled out full support for creating schedules via our GraphQL API, we're still working on the UI. If you don't mind working with the GraphQL API, then you can use the entire feature right now! To create a schedule, head on over to: graphql.buildkite.com and this (the `pipelineID` field is the ID of the pipeline returned from GraphQL)

```graphql
mutation CreateScheduleMutation {
  pipelineScheduleCreate(input: { label:"foo", cronline:"@midnight", pipelineID: "..." }) {
    pipeline {
      uuid
    }
    pipelineScheduleEdge {
      node {
        uuid
        label
        cronline
        nextBuildAt
        enabled
        createdBy {
          uuid
        }
      }
    }
  }
}
```

And to query all the schedules for a pipeline:

```graphql
query {
  pipeline(slug:"your-org/pipeline-slug") {
    schedules {
      edges {
        node {
          id
          uuid
          label
          cronline
          nextBuildAt
          message
          commit
          branch
          env
          enabled
          failedMessage
          failedAt
          createdAt
          createdBy {
            name
          }
          builds {
            edges {
              node {
                source
                uuid
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by keithpitt** [comment] 2016-07-01 22:14
We use cron to define your build schedules, in the above example I've used the shortcut `@midnight` to refer to a nightly build.

**Comment by WearyMonkey** [comment] 2016-07-20 05:40
@keithpitt what timezone is the crod defined in?

**Comment by keithpitt** [comment] 2016-07-20 05:41
@WearyMonkey all UTC!

**Comment by efung** [comment] 2016-08-16 18:43
There's an excellent [blog post](https://building.buildkite.com/tutorial-getting-started-with-graphql-queries-and-mutations-11211dfe5d64) now with more details about using the Buildkite GraphQL API to set up a nightly build.

**Comment by keithpitt** [comment] 2016-08-16 22:28
Thanks for sharing that post @efung :)

We'll keep this ticket open until we put a UI on it.

**Comment by wjlow** [comment] 2016-10-24 05:32
Would absolutely love a UI on this 👍 
Thanks for the work so far!

**Comment by keithpitt** [comment] 2016-10-24 05:43
There is a _secret_ UI that you can use right now...

https://buildkite.com/[org]/[pipeline]/settings/schedules

Let us know how you go using it! Note that the UI is considered "alpha", but it should just work :)

**Comment by wjlow** [comment] 2016-10-24 06:00
I can confirm that this works! 😍

**Comment by hamstah** [comment] 2016-11-09 17:28
Working for us too, thanks

**Comment by hamstah** [comment] 2016-11-14 12:11
FYI @keithpitt it seems that there might be a small bug in the schedule.

We were on a trial, which ran out last week, and it seems that the schedule was cancelled and not re-enabled when we paid the subscription.

The schedule page doesn't indicate the status (active/inactive).
I did edit it and re-submit the form and it fixed it, but it might be worth re-enabling them automatically or making it more obvious that the schedule has been paused/cancelled.

**Comment by hamstah** [comment] 2016-11-14 13:29
Actually, it says "next build scheduled at X" but doesn't actually run it.
Only proper fix was to create a new schedule.
schedule id is 7d819b8-c072-4054-a63a-476b62ddab7a if that can help.

**Comment by keithpitt** [comment] 2016-11-21 02:36
@hamstah hrm..that's weird! Cancelling and upgrading shouldn't affect a schedule. Was the user that originally created the schedule removed from the account before upgrading by any chance?

**Comment by hamstah** [comment] 2016-11-21 07:36
Hey
Nope, user was my account, which created the buildkite account as well as
the job and schedule.
Maybe the trial expiry temporarily suspended it?

**Comment by keithpitt** [comment] 2016-11-21 21:53
Ah yes, when the trial expired the scheduled would have errored and disabled itself. I don't think we have a way for it to re-enable itself again after an error. Sorry about that!

**Comment by brucem** [comment] 2017-02-23 00:01
Hi Guys - Great feature looks to work well.

I realise it's a very alpha feature but some UX feedback - both the schedules list and details page are missing context information about the  pipeline you are working with. Just adding the pipeline heading that's on all pipeline pages will be awesome!

**Comment by keithpitt** [comment] 2017-02-23 00:04
@brucem oh! Funny you should mention that, I'm actually working on bringing the header to those pages now!

**Comment by levi** [comment] 2017-05-12 22:57
Feature request: Would be great to be able to specify multiple branches in a schedule, which would enqueue multiple jobs at once.

**Comment by keithpitt** [comment] 2017-05-14 22:01
@levi 👋 thanks for the feedback! Wouldn't you just be able to create multiple schedules?

**Comment by keithpitt** [comment] 2017-05-14 22:02
Btw, I might close this issue since we launched the UI for schedules last week, thanks everyone for the feedback! If you have any followup ideas, feel free to create new issues so we can track them there 😄

**Closed by keithpitt** 2017-05-14 22:02 UTC
