### ISSUE TITLE
Uploading steps, concurrent builds and a single agent

### ISSUE THREAD

**Issue by navitronic** [buildkite/feedback#121] opened 2015-08-16 23:29 UTC
As mentioned in the [buildkite slack](https://buildkitechat.slack.com/archives/general/p1439447351001567):

If you're uploading your steps and end up with more than one scheduled build, the upload steps for both builds will run and then the uploaded steps get run.

So you end up with the following:

```
Build #1 gets scheduled
Build #2 gets scheduled
Build #1 upload step runs
Build #2 upload step runs
The uploaded steps of Build #1 runs (whilst Build #2 sits there spinning in the UI still)
The uploaded steps of Build #2 runs 
```

nothing goes wrong particularly, it's just confusing to see two builds "running" if you're not familiar with how the build pipeline is setup and know that there's only a single agent.

It feels like the correct outcome would be:

```
Build #1 gets scheduled
Build #2 gets scheduled
Build #1 upload step runs
The uploaded steps of Build #1 runs
Build #2 upload step runs
The uploaded steps of Build #2 runs 
```

**Comment by keithpitt** [comment] 2015-08-17 01:09
Yup, I hear ya and I know how to fix it! I'll try and get a fix out soon and I'll let you know when it's done!

**Comment by gtirloni** [comment] 2018-03-26 16:53
I'm trying to understand this myself. We have one agent and, while the interface shows 2 builds running (PRs that got submitted almost at the same time), the agent is running one build at a time.

Environment: CentOS 7.4, buildkite-agent 2.6.10.2219

**Comment by keithpitt** [comment] 2018-03-27 04:31
👋 Oh wow, this ticket is old! I'm sorry I never closed it :|

There are 2 things to note with how BK dispatches work:

- Buildkite will dispatch older jobs first (in order of `scheduled_at`)
- `buildkite-agent pipeline upload` will copy the `scheduled_at` of the uploading job to any new jobs
- Webhooks can sometimes get delivered in the wrong order (depending on how the source code provider is feeling at the time)

We also have some controls that help with concurrency. If you want to ensure that jobs are only ever executed in the order they come in, you can use the `concurrency_group` attribute:

https://buildkite.com/docs/builds/controlling-concurrency

@gtirloni with regards to the single workdir, each agent creates it's own repository. So if you've only got 1 agent on a machine, it will keep recycling the same checked out repository to run your builds. If you run 2 agents on the same machine, it'll keep 2 seperate checkouts since 2 builds can run at the same time.

The order you provided doesn't sound quite right given what you've said. If you'd like me to look into it further, can you shoot more details over to hello@buildkite.com

**Closed by keithpitt** 2018-03-27 04:31 UTC

**Comment by gtirloni** [comment] 2018-03-27 12:15
@keithpitt thanks! I'm starting to understand how it all works :) I'll try to reproduce what I've seen once more and collect the logs. Thanks again, much appreciated.
