### ISSUE TITLE
Prefer agents that have run jobs before

### ISSUE THREAD

**Issue by toolmantim** [buildkite/feedback#99] opened 2015-06-03 04:10 UTC
Currently the agent is selected to run a job based on priority then most recent check-in.

@lox wants to avoid the case of hitting cold caches when there's warm agents just sitting there waiting for work too… if an agent's run a job for a project before, it's probably going to have the git code checked out, docker layers around from pervious builds, dependent containers pulled, etc.

Perhaps a better default agent selection for everyone would be to select the agent based on 1) priority 2) most recent time since it ran a job for the same project? Basically it would leave agents to sit there cold unless needed, rather than basically an even distribution like we do now.

**Comment by keithpitt** [comment] 2015-06-03 06:29
This is a really great idea and should be trivial to implement. Will do today!

**Comment by keithpitt** [comment] 2015-06-03 06:31
Dupe of https://github.com/buildkite/terminal/issues/28

**Comment by keithpitt** [comment] 2015-06-03 17:52
I've pushed this change, and it's now in production. Thanks @lox! :dancers:

**Closed by keithpitt** 2015-06-03 17:52 UTC
